import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto_Mono } from "next/font/google";
import "./globals.css";
import { GlobalStyles } from "@/Components/GlobalStyles";
import { ToastContainer } from "react-toastify";
import AuthProvider from "@/Components/AuthProvider";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});
const robotoMono = Roboto_Mono({
    subsets: ["latin"],
    variable: "--font-roboto-mono",
});
const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
   children,
}: {
    children: React.ReactNode;
}) {

    return (
        <html lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable} ${robotoMono.variable} antialiased`}
        >
        <GlobalStyles />
        <AuthProvider>
          {children}
        </AuthProvider>
        <ToastContainer />
        </body>
        </html>
    );
}
